### ISSUE TITLE
Conditional order ids not referencing order and trade ids

### ISSUE THREAD

**Issue by micant** [ftexchange/ftx#111]
I've just started integrating my system with FTX and I'm not understanding how it's possible to find an order and the associated trades via the api, when an order is placed by a conditional order.

**Scenario:**
- Place a conditional order, save the order `id` from the response. 
- When a conditional order is triggered, check the `/conditional_orders/history` endpoint and find the conditional order with the same `id`. This conditional order is now `triggered`, and has some data properties indicating the order has executed and filled, eg. order amount and avg. price. 
- In the `/orders/history` endpoint, a _new_  order is created with a unique `id`, the `createdAt` property on this order is within milliseconds of the conditional order's `triggeredAt` property and has the same order quantities etc, so it can be assumed (but not guaranteed) this is the order that was conditionally triggered. There is no property on the new order that can be matched to the conditional order.
- Trades at  `/fills` can't be matched to the conditional order, only the new order.

**Problem**
It appears that it is not possible to identify an order made from a trigger order as there is no property binding them together. My system records and reconciles all trades and orders in a local db, so without being able to link triggers to orders, I'm left with orphaned order and trade data. 
I don't know what the solution is other than programatically taking a "likely fit" approach between trigger orders and orders, but that feels really janky and becomes highly problematic when you're trading frequently.

Am I missing something really obvious? Appreciate your help!

**Comment by giafar** [comment]
Same problem here

**Comment by micant** [comment]
For those with this question I found the solution.

When you create a conditional order, you are given an order id relevant only to the conditional order.
This can be found here - `GET /conditional_orders/history?market={market}`

When the conditional order is triggered, a new order is created with a new order id.
The new order can be found here - `GET /orders/history?market={market}`

You have two orders in your history, one "conditional"  and one "on-market". These are logically bound but have no direct reference to each other via their properties.

The endpoint that binds them together is this - `GET /conditional_orders/{conditional_order_id}/triggers`
Where the query string is the id you got from your conditional order.

The `orderId` property of the response is the order id of the "on-market" order. This `orderId` property can also be referenced on fills.

See - https://docs.ftx.com/#get-trigger-order-triggers
```
{
  "success": true,
  "result": [
    {
      "error": null,
      "filledSize": 4.0,
      "orderSize": 10.0,
      "orderId": 38066650, // on-market order id 
      "time": "2020-01-19T09:23:36.570904+00:00"
    }
  ]
}
```


@giafar 
I haven't looked into how these endpoints relate to the websocket api but hopefully this will lead you in the right direction.
