### ISSUE TITLE
"Not logged in" when attempting to get order status in python client

### ISSUE THREAD

**Issue by Abello966** [ftexchange/ftx#27]
Hello! I was trying to implement the get order status endpoint in the client.py. 
According to the [REST API documentation](https://docs.ftx.com/?python#get-order-status) it sounds simple enough right? Just add a method:

```
def get_order_status(self, order_id: str) -> dict:
        return self._get(f'/orders/{order_id}')
```

But when I test it I get Exception: Not logged in on the _process_response method

Does anyone have any idea how to fix it?

In general the python client works very well, it's been pretty easy to extend it to include other API endpoints, it was just this one that didn't work

Thanks!

**Comment by dr497** [comment]
This is what the `get_order_status` should be like 

```python
def get_order_status(self, order_id: str) -> dict:
    return self._get(f'orders/{order_id}')
```

**Comment by Abello966** [comment]
Hi @dr497, thanks for your answer. You were right, after taking the "/" off the problem disappears. I'm closing the issue now

Thanks!
