### ISSUE TITLE
{"error":"Not logged in","success":false} on sending Rest API request in C++.

### ISSUE THREAD

**Issue by rahul233343** [ftexchange/ftx#28]
I am setting up the c++ code for ftx. And I am using the c++ code from the GitHub.

I am using my API keys. But on sending the rest API request. It says "not logged in" success : false.

And on sending login request I am getting no response?

I am using everything from GitHub c++ code except keys.

**Comment by dr497** [comment]
Hey! This blog post is pretty useful for debugging authentication problem https://blog.ftx.com/blog/api-authentication/

Hope it helps!

**Comment by rahul233343** [comment]
Thanks, its working.
