### ISSUE TITLE
Interest in an FTX C# API Client?

### ISSUE THREAD

**Issue by Agorist-Action** [ftexchange/ftx#40]
Hello,

I noticed that there is no C# API in this repository. Are you seeking the creation of a REST and/or Websocket FTX C# API client? 

I have experience writing a C# API client for Monero (the cryptocurrency), which can be found on the Monero project's official website [here]( https://www.getmonero.org/resources/developer-guides/). You can find the original source-code [here](https://github.com/monero-ecosystem/csharp-monero-rpc-client).

Please let me know if you are interested. It's worth mentioning that, while the C# JSON-RPC client I wrote for Monero was a passion-project, I'd like to be compensasted for working on and delivering an FTX C# API client.

Cheers,
Agorist-Action

**Comment by McoreD** [comment]
Would love to have a C# wrapper :)

**Comment by McoreD** [comment]
Closed without a response?

**Comment by Agorist-Action** [comment]
Not sure what you meant by
> We can ask the author at https://github.com/JKorf?tab=repositories to create one!

Anyways, I posted this over 4 months ago. My workload and priorities have changed.

**Comment by McoreD** [comment]
JKorf is known for his BinanceNet API. He does it using a common interface for other exchanges can be easily implemented. Understand your priorities have changed. Same with two kids and one being an 11mo. Sorry I didn't really you were actually trying to offer creating one. I thought you were requesting.
