### ISSUE TITLE
WS has no message from channel fills and orders

### ISSUE THREAD

**Issue by chanhw3** [ftexchange/ftx#64]
I have tried lots of time with the below code but it prints nothing from get_fills and get_orders websocket (but public channel orderbook have message coming back). I have using the FtxWebsocketClient with api_key and api_secret, so i guess it should be authenticated correctly, liked what i got in Res verson.

May I know what I am missing in order to have fills and orders even i have put lots of fills and orders in the Ftx account?

Please help. Many thanks!!!!

import time
from FTX_websocket import FtxWebsocketClient
'''
#Update __init__ with the api_key and api_secret
class FtxWebsocketClient(WebsocketManager):
    _ENDPOINT = 'wss://ftx.com/ws/'

    def __init__(self, api_key=None, api_secret=None) -> None:
        super().__init__()
        self._trades: DefaultDict[str, Deque] = defaultdict(lambda: deque([], maxlen=10000))
        self._fills: Deque = deque([], maxlen=10000)
        self._api_key = api_key  # TODO: Place your API key here
        self._api_secret = api_secret  # TODO: Place your API secret here
        self._orderbook_update_events: DefaultDict[str, Event] = defaultdict(Event)
        self._reset_data()
'''

    #### Websocket client  ####
    api_key = os.environ.get('ftx_api')
    api_secret = os.environ.get('ftx_secret')

    time.sleep(2)
    ws = FtxWebsocketClient(api_key=api_key, api_secret=api_secret)
    ws.connect()
    for i in range(1, 10):
        print(ws.get_orderbook('BTC-PERP'))
        print(ws.get_fills())
        print(ws.get_orders())
        time.sleep(1)

**Comment by SujathaChristy** [comment]
Hi were u able to connect to wss://ftx.com/ws/ 
am not

**Comment by jayenashar** [comment]
My computer was attempting to use IPv6 but my ISP doesn't support IPv6.  I was able to set me computer to use IPv4 only and it started working.
