### ISSUE TITLE
Missing parameter market

### ISSUE THREAD

**Issue by Ramacap** [ftexchange/ftx#70]
def getAccount():
  
    import time, hmac
        
    s= requests.Session()
    url = "https://ftx.com/api/orders"
    ts = int(time.time()*1000)
    
    params={
              "market": "DOT-PERP",
              "side": "buy",
              "price": 31,
              "type": "limit",
              "size": 0.5,
              "reduceOnly": False,
              "ioc": False,
              "postOnly": False,
              "clientId": None
            }
    
    request=requests.Request("POST",url,params=params)
   
    prepared = request.prepare()
   
    signature_payload = f'{ts}{prepared.method}{prepared.path_url}'.encode()
    
    signature = hmac.new(api_secret.encode(),signature_payload,'sha256').hexdigest()
    
    request.headers = {'FTX-KEY':api_key,'FTX-SIGN':signature,'FTX-TS':str(ts)}
    
    r = s.send(request.prepare())
    r.json()

RESPONSE = {'success': False, 'error': 'Missing parameter market'}

pls need help, cant solve whats missing....

**Comment by gzorlee** [comment]
What was missing in the end?
